# coding: utf-8

from flaskext.wtf import Form, TextAreaField, HiddenField, BooleanField, \
        SubmitField, TextField, ValidationError, length, SelectField, \
        required, email, equal_to, regexp, optional
from flaskext.babel import gettext, lazy_gettext as _ 


langs = [
	  ('text', 'Text only'),
	  ('abap', 'ABAP'),
	  ('antlr', 'ANTLR'),
	  ('antlr-as', 'ANTLR With ActionScript Target'),
	  ('antlr-csharp', 'ANTLR With C# Target'),
	  ('antlr-cpp', 'ANTLR With CPP Target'),
	  ('antlr-java', 'ANTLR With Java Target'),
	  ('antlr-objc', 'ANTLR With ObjectiveC Target'),
	  ('antlr-perl', 'ANTLR With Perl Target'),
	  ('antlr-python', 'ANTLR With Python Target'),
	  ('antlr-ruby', 'ANTLR With Ruby Target'),
	  ('as', 'ActionScript'),
	  ('as3', 'ActionScript 3'),
	  ('apacheconf', 'ApacheConf'),
	  ('applescript', 'AppleScript'),
	  ('asy', 'Asymptote'),
	  ('bbcode', 'BBCode'),
	  ('bash', 'Bash'),
	  ('console', 'Bash Session'),
	  ('bat', 'Batchfile'),
	  ('befunge', 'Befunge'),
	  ('boo', 'Boo'),
	  ('brainfuck', 'Brainfuck'),
	  ('c', 'C'),
	  ('csharp', 'C#'),
	  ('cpp', 'C++'),
	  ('cmake', 'CMake'),
	  ('css', 'CSS'),
	  ('css+django', 'CSS+Django/Jinja'),
	  ('css+genshitext', 'CSS+Genshi Text'),
	  ('css+mako', 'CSS+Mako'),
	  ('css+myghty', 'CSS+Myghty'),
	  ('css+php', 'CSS+PHP'),
	  ('css+erb', 'CSS+Ruby'),
	  ('css+smarty', 'CSS+Smarty'),
	  ('cheetah', 'Cheetah'),
	  ('clojure', 'Clojure'),
	  ('common-lisp', 'Common Lisp'),
	  ('cython', 'Cython'),
	  ('d', 'D'),
	  ('dpatch', 'Darcs Patch'),
	  ('control', 'Debian Control file'),
	  ('sourceslist', 'Debian Sourcelist'),
	  ('delphi', 'Delphi'),
	  ('diff', 'Diff'),
	  ('django', 'Django/Jinja'),
	  ('dylan', 'Dylan'),
	  ('erb', 'ERB'),
	  ('ragel-em', 'Embedded Ragel'),
	  ('erlang', 'Erlang'),
	  ('erl', 'Erlang erl session'),
	  ('evoque', 'Evoque'),
	  ('fortran', 'Fortran'),
	  ('gas', 'GAS'),
	  ('glsl', 'GLSL'),
	  ('genshi', 'Genshi'),
	  ('genshitext', 'Genshi Text'),
	  ('pot', 'Gettext Catalog'),
	  ('Cucumber', 'Gherkin'),
	  ('gnuplot', 'Gnuplot'),
	  ('go', 'Go'),
	  ('groff', 'Groff'),
	  ('html', 'HTML'),
	  ('html+cheetah', 'HTML+Cheetah'),
	  ('html+django', 'HTML+Django/Jinja'),
	  ('html+evoque', 'HTML+Evoque'),
	  ('html+genshi', 'HTML+Genshi'),
	  ('html+mako', 'HTML+Mako'),
	  ('html+myghty', 'HTML+Myghty'),
	  ('html+php', 'HTML+PHP'),
	  ('html+smarty', 'HTML+Smarty'),
	  ('haskell', 'Haskell'),
	  ('ini', 'INI'),
	  ('irc', 'IRC logs'),
	  ('io', 'Io'),
	  ('java', 'Java'),
	  ('jsp', 'Java Server Page'),
	  ('js', 'JavaScript'),
	  ('js+cheetah', 'JavaScript+Cheetah'),
	  ('js+django', 'JavaScript+Django/Jinja'),
	  ('js+genshitext', 'JavaScript+Genshi Text'),
	  ('js+mako', 'JavaScript+Mako'),
	  ('js+myghty', 'JavaScript+Myghty'),
	  ('js+php', 'JavaScript+PHP'),
	  ('js+erb', 'JavaScript+Ruby'),
	  ('js+smarty', 'JavaScript+Smarty'),
	  ('llvm', 'LLVM'),
	  ('lighty', 'Lighttpd configuration file'),
	  ('lhs', 'Literate Haskell'),
	  ('logtalk', 'Logtalk'),
	  ('lua', 'Lua'),
	  ('moocode', 'MOOCode'),
	  ('mxml', 'MXML'),
	  ('basemake', 'Makefile'),
	  ('make', 'Makefile'),
	  ('mako', 'Mako'),
	  ('matlab', 'Matlab'),
	  ('matlabsession', 'Matlab session'),
	  ('minid', 'MiniD'),
	  ('modelica', 'Modelica'),
	  ('trac-wiki', 'MoinMoin/Trac Wiki markup'),
	  ('mupad', 'MuPAD'),
	  ('mysql', 'MySQL'),
	  ('myghty', 'Myghty'),
	  ('nasm', 'NASM'),
	  ('newspeak', 'Newspeak'),
	  ('nginx', 'Nginx configuration file'),
	  ('numpy', 'NumPy'),
	  ('ocaml', 'OCaml'),
	  ('objective-c', 'Objective-C'),
	  ('ooc', 'Ooc'),
	  ('php', 'PHP'),
	  ('pov', 'POVRay'),
	  ('perl', 'Perl'),
	  ('prolog', 'Prolog'),
	  ('python', 'Python'),
	  ('python3', 'Python 3'),
	  ('py3tb', 'Python 3.0 Traceback'),
	  ('pytb', 'Python Traceback'),
	  ('pycon', 'Python console session'),
	  ('rebol', 'REBOL'),
	  ('rhtml', 'RHTML'),
	  ('ragel', 'Ragel'),
	  ('ragel-c', 'Ragel in C Host'),
	  ('ragel-cpp', 'Ragel in CPP Host'),
	  ('ragel-d', 'Ragel in D Host'),
	  ('ragel-java', 'Ragel in Java Host'),
	  ('ragel-objc', 'Ragel in Objective C Host'),
	  ('ragel-ruby', 'Ragel in Ruby Host'),
	  ('raw', 'Raw token data'),
	  ('redcode', 'Redcode'),
	  ('rb', 'Ruby'),
	  ('rbcon', 'Ruby irb session'),
	  ('splus', 'S'),
	  ('sql', 'SQL'),
	  ('scala', 'Scala'),
	  ('scheme', 'Scheme'),
	  ('smalltalk', 'Smalltalk'),
	  ('smarty', 'Smarty'),
	  ('squidconf', 'SquidConf'),
	  ('tcl', 'Tcl'),
	  ('tcsh', 'Tcsh'),
	  ('tex', 'TeX'),
	  ('vb.net', 'VB.net'),
	  ('vala', 'Vala'),
	  ('vim', 'VimL'),
	  ('xml', 'XML'),
	  ('xml+cheetah', 'XML+Cheetah'),
	  ('xml+django', 'XML+Django/Jinja'),
	  ('xml+evoque', 'XML+Evoque'),
	  ('xml+mako', 'XML+Mako'),
	  ('xml+myghty', 'XML+Myghty'),
	  ('xml+php', 'XML+PHP'),
	  ('xml+erb', 'XML+Ruby'),
	  ('xml+smarty', 'XML+Smarty'),
	  ('xslt', 'XSLT'),
	  ('yaml', 'YAML'),
	  ('aspx-cs', 'aspx-cs'),
	  ('aspx-vb', 'aspx-vb'),
	  ('c-objdump', 'c-objdump'),
	  ('cpp-objdump', 'cpp-objdump'),
	  ('d-objdump', 'd-objdump'),
	  ('objdump', 'objdump'),
	  ('rst', 'reStructuredText'),
	  ('sqlite3', 'sqlite3con'),
    ]

class GistForm(Form):

    code_type = SelectField(_("Language"), validators=[required(message=_("Language required"))], choices=langs)
    desc = TextAreaField(_("Brief"), validators=[ required(message=_("Description required")), 
        length(max=140, message=_("Pls. less than 140 charactaer"))])
    content = TextAreaField(_("Code"), validators=[required(message=_("Code required"))])
    tags = TextField(_("Tags"), validators=[ required(message=_("Tags required"))])
    submit = SubmitField(_("Commit"))
